version: "3"

services:
  tcc:
    image: streamlit-docker
    build:
        dockerfile: ./Dockerfile
        context: .
    # command: streamlit run st_app.py --server.port 80
    environment:
        - PORT=${PORT}
    ports:
        - ${PORT}:${PORT}